# Generated by Django 6.0 on 2025-12-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_file_message_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
    ]
