# Generated by Django 6.0 on 2026-01-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_room_alter_message_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
